development:
  db_username: [db_username]
  db_password: [db_password]
  secret_key_base: [generate some secret key base --> rails secret]
  telegram:
    bot: 'your telegram token here'
  wit:
    token: 'your wit.ai token here'

production:
  db_username: [db_username]
  db_password: [db_password]
  secret_key_base: [generate some secret key base --> rails secret]
  telegram:
    bot: 'your telegram token here'
  wit:
    token: 'your wit.ai token here'